CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
	login VARCHAR(20) NOT NULL,
	password VARCHAR(200) NOT NULL,
	fio VARCHAR(60) NOT NULL,
	email VARCHAR(60),
	rights INTEGER NOT NULL DEFAULT 1,
	UNIQUE(login)
);